/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.nurflugel.releasetracker

class PresentationApp {
  companion object {
    @JvmStatic
    fun main(args: Array<String>) {
      runTheApp(args)
    }

    private fun runTheApp(args: Array<String>) {
      val data: List<DataRecord> = loadData(args)
      presentData(data)
    }

    private fun loadData(args: Array<String>): List<DataRecord> {
      TODO("Not yet implemented")
    }

    private fun presentData(filteredData: List<DataRecord>) {
      // create filter criteria - author, commit message match (story number), app(s), or all - also specify a time limit
      TODO("Not yet implemented")
    }
  }
}
