/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */
import org.jooq.meta.jaxb.ForcedType
import org.jooq.meta.jaxb.Logging
import org.jooq.meta.jaxb.Property

var KOTEST_VERSION = "5.5.4"

plugins {
  // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
  kotlin("jvm") version "1.8.0"

  // Apply the application plugin to add support for building a CLI application in Java.
  application
  id("org.springframework.boot") version "3.0.1"

  id("com.github.ben-manes.versions") version "0.44.0"
  id("com.dorongold.task-tree") version "2.1.1"

//  id("nu.studer.jooq") version "8.1"
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

//buildscript {
//  dependencies {
//    classpath("org.jooq:jooq-codegen:3.17.6")
//    classpath("com.h2database:h2:200")
//  }
//}

val databaseLibrary = "com.h2database:h2:2.1.214"

dependencies {
  implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
  // This dependency is used by the application.
  implementation("com.google.guava:guava:31.1-jre")
  implementation("org.jooq:jooq:3.17.6")

  implementation(databaseLibrary)
  //  testImplementation("junit:junit:4.11")

  implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

  testImplementation("io.kotest:kotest-runner-junit5:$KOTEST_VERSION")
  testImplementation("io.kotest:kotest-assertions-core:$KOTEST_VERSION")
  testImplementation("io.kotest:kotest-property:$KOTEST_VERSION")

//  jooqGenerator(databaseLibrary)
  //todo add flyway lib and task section
}

//apply ("jooq.gradle.kts")

testing {
  suites {
    // Configure the built-in test suite
    val test by getting(JvmTestSuite::class) {
      // Use Kotlin Test test framework
      useKotlinTest("1.8.0")

      dependencies {
        // Use newer version of JUnit Engine for Kotlin Test
        implementation("org.junit.jupiter:junit-jupiter-engine:5.9.2")
      }
    }
  }
}

application {
  // Define the main class for the application.
  mainClass.set("com.nurflugel.releasetracker.AppKt")
  group = "com.nurflugel"
  version = "0.0.1-SNAPSHOT"
}

//jooq {
//  version.set("3.17.6")  // default (can be omitted)
//  edition.set(nu.studer.gradle.jooq.JooqEdition.OSS)  // default (can be omitted)
//
//  configurations {
//    create("main") {  // name of the jOOQ configuration
//      generateSchemaSourceOnCompilation.set(true)  // default (can be omitted)
//
//      jooqConfiguration.apply {
//        logging = Logging.WARN
//        jdbc.apply {
//          driver = "org.postgresql.Driver"
//          url = "jdbc:postgresql://localhost:5432/sample"
//          user = "some_user"
//          password = "some_secret"
//          properties.add(Property().apply {
//            key = "ssl"
//            value = "true"
//          })
//        }
//        generator.apply {
//          name = "org.jooq.codegen.DefaultGenerator"
//          database.apply {
//            name = "org.jooq.meta.postgres.PostgresDatabase"
//            inputSchema = "public"
//            forcedTypes.addAll(listOf(
//              ForcedType().apply {
//                name = "varchar"
//                includeExpression = ".*"
//                includeTypes = "JSONB?"
//              },
//              ForcedType().apply {
//                name = "varchar"
//                includeExpression = ".*"
//                includeTypes = "INET"
//              }
//            ))
//          }
//          generate.apply {
//            isDeprecated = false
//            isRecords = true
//            isImmutablePojos = true
//            isFluentSetters = true
//          }
//          target.apply {
//            packageName = "nu.studer.sample"
//            directory = "build/generated-src/jooq/main"  // default (can be omitted)
//          }
//          strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
//        }
//      }
//    }
//  }
//}
