version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "releaseTracker"
      POSTGRES_USER: "me"
      POSTGRES_PASSWORD: "noPassword"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: postgres-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"